"""Rename user_id to patient_id in medical_reports table

Revision ID: ad1d38f25555
Revises: b82b49bf51ab
Create Date: 2026-03-23 21:16:03.331251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad1d38f25555'
down_revision: Union[str, Sequence[str], None] = 'b82b49bf51ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_reports', sa.Column('patient_id', sa.String(length=50), nullable=False))
    op.drop_column('medical_reports', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_reports', sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('medical_reports', 'patient_id')
    # ### end Alembic commands ###
