"""Update embedding column to use VECTOR type

Revision ID: b82b49bf51ab
Revises: d504d0db5e6f
Create Date: 2026-03-23 21:05:57.415389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b82b49bf51ab'
down_revision: Union[str, Sequence[str], None] = 'd504d0db5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除现有的embedding列（JSONB类型）
    op.drop_column('report_chunks', 'embedding')
    # 重新创建embedding列（VECTOR类型）
    op.add_column('report_chunks', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除现有的embedding列（VECTOR类型）
    op.drop_column('report_chunks', 'embedding')
    # 重新创建embedding列（JSONB类型）
    op.add_column('report_chunks', sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###
